# Generated by Django 4.2.1 on 2024-03-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_mobile', models.CharField(max_length=12)),
                ('user_email', models.EmailField(max_length=254)),
                ('driver_name', models.CharField(max_length=30)),
                ('driving_license_no', models.CharField(max_length=30)),
                ('driving_license', models.FileField(upload_to='documents/')),
                ('vehicle_insurance', models.FileField(upload_to='documents/')),
                ('rc_book', models.FileField(upload_to='documents/')),
                ('address_proof', models.FileField(upload_to='documents/')),
                ('cancelled_cheque', models.FileField(upload_to='documents/')),
                ('fitness_certificate', models.FileField(upload_to='documents/')),
                ('u_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
            ],
        ),
    ]
